### ISSUE TITLE
Mysql: Can't convert geometries of type org.geolatte.geom.LinearRing

### ISSUE THREAD

**Issue by xak2000** [GeoLatte/geolatte-geom#152]
This code works in 1.7.0:

```java
WkbEncoder encoder = Wkb.newEncoder(Wkb.Dialect.MYSQL_WKB);

PositionSequence<G2D> seq = PositionSequenceBuilders.fixedSized(5, G2D.class)
	.add(geoRectangle.getNortheast().getLon().asDouble(), geoRectangle.getNortheast().getLat().asDouble())
	.add(geoRectangle.getNorthwest().getLon().asDouble(), geoRectangle.getNorthwest().getLat().asDouble())
	.add(geoRectangle.getSouthwest().getLon().asDouble(), geoRectangle.getSouthwest().getLat().asDouble())
	.add(geoRectangle.getSoutheast().getLon().asDouble(), geoRectangle.getSoutheast().getLat().asDouble())
	.add(geoRectangle.getNortheast().getLon().asDouble(), geoRectangle.getNortheast().getLat().asDouble())
	.toPositionSequence(); // basically a closed LINESTRING

Geometry<G2D> geometry = Geometries.mkLinearRing(seq, CoordinateReferenceSystems.WGS84);
ByteBuffer buffer = encoder.encode(geometry, ByteOrder.NDR);
```

After upgrading to 1.8.2 (also tried 1.8.0) `encoder.encode(...)` throws:

```
org.geolatte.geom.codec.UnsupportedConversionException: Can't convert geometries of type org.geolatte.geom.LinearRing
	at org.geolatte.geom.codec.WkbDialect.geometryTypeCode(WkbDialect.java:127) ~[geolatte-geom-1.8.2.jar:na]
	at org.geolatte.geom.codec.BaseWkbVisitor.writeTypeCodeAndSrid(BaseWkbVisitor.java:136) ~[geolatte-geom-1.8.2.jar:na]
	at org.geolatte.geom.codec.BaseWkbVisitor.visit(BaseWkbVisitor.java:78) ~[geolatte-geom-1.8.2.jar:na]
	at org.geolatte.geom.LineString.accept(LineString.java:114) ~[geolatte-geom-1.8.2.jar:na]
	at org.geolatte.geom.codec.MySqlWkbEncoder.encode(MySqlWkbEncoder.java:42) ~[geolatte-geom-1.8.2.jar:na]
```

**Comment by xak2000** [comment]
I think I found a root of this error.

Previously in 1.7.0 [this method](https://github.com/GeoLatte/geolatte-geom/blob/38cd2552de844c805a91035f5eed669d8c38e242/geom/src/main/java/org/geolatte/geom/codec/WkbVisitor.java#L121) was used to get geometry type. This method correctly handles class inheritance and detects that type of `LinearRing` class (that inherits from `LineString` class) is `LINE_STRING`.

New logic introduced in 1.8.0 changed this and now inheritance is not handled.

**Comment by maesenka** [comment]
Thanks for the report, and diagnosis. It's fixed now in branch master. I'll make a release soon.

**Comment by xak2000** [comment]
@maesenka Hello! Do you have any expectations about new release date?
