### ISSUE TITLE
bug in support mysql's MultiLineString type

### ISSUE THREAD

**Issue by magicdoom** [GeoLatte/geolatte-geom#30]
Only MultiLineString type in mysql is not support.

**Comment by magicdoom** [comment]
Caused by: java.lang.IllegalArgumentException: Type code 0 is not known.
	at org.geolatte.geom.codec.WkbGeometryType.parse(WkbGeometryType.java:67)
	at org.geolatte.geom.codec.AbstractWkbDecoder.decodeGeometry(AbstractWkbDecoder.java:60)
	at org.geolatte.geom.codec.AbstractWkbDecoder.decodeMultiLineString(AbstractWkbDecoder.java:86)
	at org.geolatte.geom.codec.AbstractWkbDecoder.decodeGeometry(AbstractWkbDecoder.java:77)
	at org.geolatte.geom.codec.AbstractWkbDecoder.decode(AbstractWkbDecoder.java:49)
