### ISSUE TITLE
Exception in GeolatteModule in latest release

### ISSUE THREAD

**Issue by bushaev** [GeoLatte/geolatte-geom#74]
To reproduce:

```
import com.fasterxml.jackson.databind.ObjectMapper;
import org.geolatte.geom.json.GeolatteGeomModule;

public class Main {
    public static void main(String[] args) {
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.registerModule(new GeolatteGeomModule());
    }
}
```

Throws the following exception:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/geolatte/geom/Feature
	at org.geolatte.geom.json.GeolatteGeomModule.<init>(GeolatteGeomModule.java:50)
	at org.geolatte.geom.json.GeolatteGeomModule.<init>(GeolatteGeomModule.java:30)
	at ru.krontech.aisnet.web.Main.main(Main.java:10)
Caused by: java.lang.ClassNotFoundException: org.geolatte.geom.Feature
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more
```

**Comment by bushaev** [comment]
Sorry, looks like i messed up with dependencies
